controller_manager:
  ros__parameters:
    update_rate: 1000  # Hz
    use_sim_time: true

    arm_group_controller:
      type: joint_trajectory_controller/JointTrajectoryController


    #hand_group_controller:
    #  type: joint_trajectory_controller/JointTrajectoryController


    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

arm_group_controller:
  ros__parameters:
    joints:
      - joint_1
      - joint_2
      - joint_3
      - joint_4
      - joint_5
      - joint_6
      #- joint_7
      #- joint_8
    command_interfaces:
      -	velocity
      - position
    state_interfaces:
      - position
      - velocity

ee_group_controller:
  ros__parameters:
    joints:
      - joint_7
    command_interfaces:
      - position
    state_interfaces:
      - position
      
#hand_group_controller:
#  ros__parameters:
#    joints: 
#      - joint_6
#    command_interfaces:
#      - position
#    state_interfaces:
#      - position
#     - velocity
