controller_manager:
  ros__parameters:
    update_rate: 100  # Hz
    #use_sim_time: false

    arm_group_steppers_controller:
      type: joint_trajectory_controller/JointTrajectoryController
      
    arm_group_servos_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

arm_group_steppers_controller:
  ros__parameters:
    joints:
      - joint_1
      - joint_2	
      - joint_3
    command_interfaces:
      - velocity
    state_interfaces:
      - position
      - velocity
    
    state_publish_rate: 100.0
    action_monitor_rate: 100.0
    constraints:
      allowed_start_tolerance: 0.02
      stopped_velocity_tolerance: 0.01
      goal_time: 0.0
    gains:
      joint_1:
        ff_velocity_scale : 1.0
        p: 0.8
        d: 0. 
      joint_2:
        ff_velocity_scale : 1.0
        p: 0.8
        d: 0.
        i: 1.0       
      joint_3:
        ff_velocity_scale : 1.0
        p: 0.8
        d: 0.01
        i: 0.7
        
arm_group_servos_controller:
  ros__parameters:
    joints:
      - joint_4
      - joint_5
      - joint_6
    command_interfaces:
      - velocity
    state_interfaces:
      - position
      - velocity
    state_publish_rate: 100.0
    action_monitor_rate: 100.0
    constraints:
      stopped_velocity_tolerance: 0.02
      goal_time: 0.0
    gains:
      joint_4:
        p: 5.0
      joint_5:
        p: 5.0
      joint_6:
        p: 5.0
