# MoveIt uses this configuration for controller management

trajectory_execution:
  allowed_execution_duration_scaling: 10.
  allowed_goal_duration_margin: 1.0
  allowed_start_tolerance: 0.02
moveit_controller_manager: moveit_simple_controller_manager/MoveItSimpleControllerManager

moveit_simple_controller_manager:
  controller_names:
    - arm_group_controller

  arm_group_controller:
    type: FollowJointTrajectory
    action_ns: follow_joint_trajectory
    default: true
    joints:
      - joint_7
      - joint_1
      - joint_2
      - joint_3
      - joint_4
      - joint_5
      - joint_6

    action_ns: follow_joint_trajectory
    default: true

